server:
  port: 8761

# eureka 配置
eureka:
  client:
    ## 是否要注册自己
    register-with-eureka: false
    # 是否获取其他 Eureka Server 服务的数据
    fetch-registry: false
    ## 当前注册中心的访问地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
